# Environment Configuration
environment:
  type: "CarRacing"
  seed: 42
  render_mode: "rgb_array"

# Monte Carlo Tree Search (MCTS) configuration
training_data_generator:
  num_episodes: 2                   # total number of episodes for self-play/learning
  max_steps_per_episode: 2
  total_time: 3600
  mcts:
      selection_strategy: "puct"          # can be "uct" or "puct"
      max_iterations: 1000                       # maximum iterations (set to 0 if using time-based termination)
      max_time: 10.0                      # maximum search time per move (in seconds)


# Training hyperparameters
training:
  learning_rate: 0.001
  epochs: 100
  batch_size: 32
  betas: [0.9, 0.999]
  look_back: 4                        # number of past states to include in the input sequence
  roll_ahead: 1

# Neural network configurations 
networks:
  representation:
    latent_shape: [6, 6, 3] 
    layers:
      - type: "conv"
        out_channels: 32
        kernel_size: 3
        stride: 1
        padding: 1
        activation: "relu"
      - type: "conv"
        out_channels: 64
        kernel_size: 3
        stride: 1
        padding: 1
        activation: "relu"
      - type: "linear"
        out_channels: 128
        activation: "tanh"
  dynamics:
    layers:
      - type: "linear"
        out_channels: 128
        activation: "relu"
      - type: "linear"
        out_channels: 128
        activation: "tanh"
  prediction:
    layers:
      - type: "linear"
        out_channels: 64
        activation: "relu"
      - type: "linear"
        out_channels: 1
        activation: "none"

