connect_four_config:
  render_mode: 'rgb_array'
  seed: 42

car_racing_config:
  render_mode: 'rgb_array'
  seed: 42

# Monte Carlo Tree Search (MCTS) configuration
mcts:
  selection_strategy: "puct"          # can be "uct" or "puct"
  max_itr: 1000                       # maximum iterations (set to 0 if using time-based termination)
  max_time: 10.0                      # maximum search time per move (in seconds)

# Environment configuration
environment:
  config_name: "car_racing_config" 

# Training hyperparameters
training:
  num_episodes: 10000                 # total number of episodes for self-play/learning
  look_back: 4                        # number of past states to include in the input sequence
  roll_ahead: 1
  total_time: 3600 
  learning_rate: 0.001
  betas: (0.9, 0.999)

# Neural network configurations
neural_networks:
  representation:
    latent_dim: 128                     # dimension of latent space
    layers:
      # TODO
      - filters: 32
        kernel_size: 3
        stride: 1
        padding: 1
      - filters: 64
        kernel_size: 3
        stride: 1
        padding: 1

  dynamics:
    layers:
      # TODO

  prediction:
    common_layers:

    # Policy head: predicts a probability distribution over actions
    policy_tower_layers:
    # Value head: predicts a scalar value for the state
    value_tower_layers:

